Python/Vectipy/app/__init__.py
from flask import Flask, render_template

import os
import toml
import psycopg2.extras

from .mvtserver import Pg2mvt

def page_not_found(e):
  return render_template('404.html'), 404

def create_app():
    app = Flask(__name__)
    app.secret_key = os.environ.get('SECRET_KEY','testingSssecretKey')
    default_config={
        'TILES':{
            'MAX_FEATURES': 2000,
            'SRID' : 4326,
            'EXTENT' : 4096,
            'BUFFER' : 256
        },
        'DEFAULT_SCHEMA':'public'
    }
    app.config.update(default_config)
    with open('config.toml', 'r') as f:
         app.config.update(toml.load(f) )
    app.config['DB']={
        'host' : os.getenv('PG_HOST'),
        'port' : os.getenv('PG_PORT'),
        'database' : os.getenv('PG_DATABASE'),
        'user' : os.getenv('PG_USER'),
        'password' : os.getenv('PG_PASSWORD'),
        'cursor_factory': psycopg2.extras.RealDictCursor
    }
    app.config['DEFAULT_SCHEMA'] = 'public'
    app.pg2mvt = Pg2mvt(app.config['DB'] )
    from app.routes import geo
    app.register_blueprint(geo)
    app.register_error_handler(404, page_not_found)
    app.config['layers'] = app.pg2mvt.scandb()
    try:
        with open('app/motd.txt','r') as f:
            print(f.read())
    except FileNotFoundError:
        pass
    print('{} geo-layers found'.format(len(app.config['layers'].get('layer',list()))) )
    return app

Python/Vectipy/app/routes.py
from flask import render_template,request, flash,url_for,redirect,Response, session,abort,Blueprint, current_app,send_file,redirect,send_from_directory, make_response, jsonify
geo = Blueprint('geo', __name__, url_prefix='/',static_folder='static', template_folder='templates')

import toml



@geo.route('/')
def loaded_layers():
    return Response( toml.dumps( current_app.config['layers'] ), mimetype='text/plain' )

@geo.route('/map/<string:layer>')
def route_map(layer):
    schema = current_app.config['DEFAULT_SCHEMA']
    if '.' in layer :
        schema = layer.split('.')[0]
        layer = layer.split('.')[1]
    return render_template('map.html',layer_name="{}.{}".format(schema,layer)) 


@geo.route('/<string:layer>/<int:z>/<int:x>/<int:y>.pbf', methods=['GET'])
def generic_mvt(layer, z, x, y):
    schema = current_app.config['DEFAULT_SCHEMA']
    if '.' in layer :
        schema = layer.split('.')[0]
        layer = layer.split('.')[1]
    
    layer_info = current_app.pg2mvt.get_layer_info(layer,current_app.config['layers'], schema = schema )    
    
    srid = int(request.args.get('srid', current_app.config['TILES']['SRID'] ))
    extent = int(request.args.get('extent', current_app.config['TILES']['EXTENT'] ))
    buffer = int(request.args.get('buffer', current_app.config['TILES']['BUFFER'] ))
    clip = bool(request.args.get('clip', True))
    tile = current_app.pg2mvt.load_tile(layer, x, y, z, schema = schema, columns=layer_info['columns'], geom_column=layer_info['geom'], extent=extent)
    response = make_response(tile)
    response.headers.add('Content-Type', 'application/octet-stream')
    response.headers.add('Access-Control-Allow-Origin', '*')
    return response


@geo.route('/scanlayer/', methods=['GET'] ) #A passer en CLI
def scanlayer():
    return Response(toml.dumps( scandb() ), mimetype='text/plain')

@geo.route('/<string:layer>.json', methods=['GET'])
def tilejson_metadata(layer): 
    schema = current_app.config['DEFAULT_SCHEMA']
    if '.' in layer :
        schema = layer.split('.')[0]
        layer = layer.split('.')[1]
    print(request.url_root)
    response = jsonify( current_app.pg2mvt.tilejson(layer, request.url_root, schema=schema) )
    response.headers.add('Access-Control-Allow-Origin', '*')
    return response

@geo.route('/<string:layer>.geojson', methods=['GET'])
def geojson(layer):
    schema = current_app.config['DEFAULT_SCHEMA']
    if '.' in layer :
        schema = layer.split('.')[0]
        layer = layer.split('.')[1]
    layer_info = current_app.pg2mvt.get_layer_info(layer,current_app.config['layers'], schema = schema ) 
    response = jsonify( current_app.pg2mvt.geojson(layer, columns=layer_info['columns'], schema=schema) ) 
    response.headers.add('Access-Control-Allow-Origin', '*')  
    return response

Python/Vectipy/app/templates/map.html
<html>
<head>
  <script src="https://cdn.maptiler.com/maplibre-gl-js/v1.13.0-rc.4/mapbox-gl.js"></script>
  <link href="https://cdn.maptiler.com/maplibre-gl-js/v1.13.0-rc.4/mapbox-gl.css" rel="stylesheet" />

  <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>

  <style>
    #map {position: absolute; top: 0; right: 0; bottom: 0; left: 0;}
  </style>

</head>



<body>
  <div id="map"></div>

<script>
    // You can remove the following line if you don't need support for RTL (right-to-left) labels:
    //mapboxgl.setRTLTextPlugin('https://cdn.maptiler.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.1.2/mapbox-gl-rtl-text.js');
    var map = new mapboxgl.Map({
      container: 'map',
      style: "https://openmaptiles.geo.data.gouv.fr/styles/osm-bright/style.json",
      center:  [-74.5, 40],
      zoom: 1.28,
      boxZoom:true
    });

    map.on('load', function () {

        map.addSource('my-data', {
        type: 'vector',
        url:"{{ url_for('geo.tilejson_metadata',layer=layer_name) }}",
        });
        map.addLayer(
           { 'type':'circle', 'source': 'my-data', 'id':'{{ layer_name }}_pt',  'source-layer' :'{{ layer_name }}',
             'filter': ['==', '$type', 'Point']
         });

        map.addLayer(
           { 'type':'fill', 'source': 'my-data', 'id':'{{ layer_name }}_pg',  'source-layer' :'{{ layer_name }}',
             'filter': ['==', '$type', 'Polygon'],
            'paint': {
            'fill-color': '#088',
            'fill-opacity': 0.8
            }
         });

        map.addLayer(
           { 'type':'line', 'source': 'my-data', 'id':'{{ layer_name }}_ln',  'source-layer' :'{{ layer_name }}',
             'filter': ['==', '$type', 'LineString'],
            'paint': {
            'line-color': '#088', 'line-width': 2.5
            }
         });  //TODO voir si c'est posslble de le faire avec 1 seul layer : soit avec un style qui filtre tout seul, soit en détectant le type de geom (mais si mutligeom ?)

    });

    map.on('sourcedata', function(e){ //Déclenché 3 fois et un peu n'importe quand..
        if (e.isSourceLoaded && e.sourceId=='my-data'){
            console.log(map.getSource('my-data').bounds );
            map.fitBounds(map.getSource('my-data').bounds);
        }
    });


    function popup(e){
        var coordinates = e.features[0].geometry.coordinates.slice();
        var html='<ul>';
        $.each( e.features[0].properties, function(k, v){
                html+='<li><b>'+k+'</b> : '+v+'</li>'
         });
        html+='</ul>'
        new mapboxgl.Popup()
        .setLngLat(e.lngLat)
        .setHTML(html)
        .addTo(map);
    }

    map.on('click', '{{ layer_name }}_ln', function (e) {
        popup(e);
    });
    map.on('click', '{{ layer_name }}_pg', function (e) {
        popup(e);
    });
    map.on('click', '{{ layer_name }}_pt', function (e) {
        popup(e);
    });

    map.on('mouseenter', '{{ layer_name }}_ln', function () {
        map.getCanvas().style.cursor = 'pointer';
    });
    map.on('mouseleave', '{{ layer_name }}_ln', function () {
        map.getCanvas().style.cursor = '';
    });

    map.on('mouseenter', '{{ layer_name }}_pg', function () {
        map.getCanvas().style.cursor = 'pointer';
    });
    map.on('mouseleave', '{{ layer_name }}_pg', function () {
        map.getCanvas().style.cursor = '';
    });

    map.on('mouseenter', '{{ layer_name }}_pt', function () {
        map.getCanvas().style.cursor = 'pointer';
    });
    map.on('mouseleave', '{{ layer_name }}_pt', function () {
        map.getCanvas().style.cursor = '';
    });
  </script>

</body>


</html>